In [1]:
# Apply Hierarchical Clustering algorithm to cluster a set of data stored in a .CSV file. Use the same 
# data set for clustering using k-Means algorithm. Compare the results of these two algorithms and 
# comment on the quality of clustering. 

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
rt = pd.read_csv('realest.csv')

In [4]:
rt.head()

Price  Bedroom   Space  Room   Lot     Tax  Bathroom  Garage  Condition
0   53.0      2.0   967.0   5.0  39.0   652.0       1.5     0.0        0.0
1   55.0      2.0   815.0   5.0  33.0  1000.0       1.0     2.0        1.0
2   56.0      3.0   900.0   5.0  35.0   897.0       1.5     1.0        0.0
3   58.0      3.0  1007.0   6.0  24.0   964.0       1.5     2.0        0.0
4   64.0      3.0  1100.0   7.0  50.0  1099.0       1.5     1.5        0.0

In [5]:
rt.dtypes

Price        float64
Bedroom      float64
Space        float64
Room         float64
Lot          float64
Tax          float64
Bathroom     float64
Garage       float64
Condition    float64
dtype: object

In [6]:
rt.isnull().sum().sum()

38

In [7]:
rt.fillna(value = 0,inplace = True)

In [8]:
rt.isnull().sum().sum()

0

In [10]:
rt.to_csv(r"C:\Users\kittu\Documents\ML Data Set\WEEK_6.ipynb")

In [11]:
x = rt.drop(['Condition'],1)
y = rt['Condition']

In [12]:
from sklearn.cluster import AgglomerativeClustering
model = AgglomerativeClustering(n_clusters = 2, affinity = 'euclidean',linkage = 'ward')

In [13]:
model.fit(x)

AgglomerativeClustering(affinity='euclidean')

In [14]:
y_pred = model.labels_
y_pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1], dtype=int64)

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm = confusion_matrix(y,y_pred)
print(cm)

print(accuracy_score(y,y_pred))

[[ 11 110]
 [  6  30]]
0.2611464968152866


In [16]:
from sklearn.cluster import KMeans

In [17]:
model=KMeans(n_clusters=3,init='k-means++',max_iter=10,n_init=1,verbose=0, random_state=1)

In [18]:
model.fit(x)

KMeans(max_iter=10, n_clusters=3, n_init=1, random_state=1)

In [19]:
y_pred1 = model.predict(x)
y_pred1

array([2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 0, 0, 2, 2, 2, 2, 0, 2, 2, 0, 0,
       2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 0, 0, 2, 2, 2, 2, 2,
       2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 2, 2, 1, 2, 1, 1, 0, 2, 2,
       2, 2, 0, 2, 2, 2, 0, 0, 2, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 1,
       1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 0, 1, 1, 0, 0, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 1, 1, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0,
       0, 2, 0])

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm = confusion_matrix(y,y_pred1)
print(cm)

print(accuracy_score(y,y_pred1))

[[38 11 72]
 [10  6 20]
 [ 0  0  0]]
0.2802547770700637


In [22]:
print('Accuracy we get from hierachical clustering algorithm is 0.26 which is less than that of accuracy we get from KMEANS algorithm that is 0.28 on same data-set (realest data-set)')

Accuracy we get from hierachical clustering algorithm is 0.26 which is less than that of accuracy we get from KMEANS algorithm that is 0.28 on same data-set (realest data-set)
