In [1]:
# Build an Artificial Neural Network by implementing the Backpropagation algorithm and test the same 
# using appropriate data sets.

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)


X = X/np.amax(X,axis=0) 
y = y/100 

print(X)
print(y)


[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [4]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))
def derivatives_sigmoid(x):
    return x * (1 - x)

In [5]:
epoch = 5
lr = 0.1
inputlayer_neurons = 2
hiddenlayer_neurons = 2
output_neurons = 1

In [6]:
wh = np.random.uniform(size = (inputlayer_neurons,hiddenlayer_neurons))
bh = np.random.uniform(size = (1,hiddenlayer_neurons))

In [7]:
wout = np.random.uniform(size = (hiddenlayer_neurons,output_neurons))
bout = np.random.uniform(size = (1,output_neurons))

In [10]:
for i in range(epoch):
#     forward 
    hinp1 = np.dot(X,wh)
    hinp = hinp1 + bh
    hlayer_act = sigmoid(hinp)
    outinp1 = np.dot(hlayer_act,wout)
    outinp = outinp1 + bout
    output = sigmoid(outinp)
    
#     Backward
    EO = y - output
    outgrad = derivatives_sigmoid(output)
    d_out = EO * outgrad
    EH = d_out.dot(wout.T)
    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad
    
    wout += hlayer_act.T.dot(d_out) * lr
    wh += X.T.dot(d_hiddenlayer) * lr
    
    print("----- EPOCH",i+1,"Starts--------")
    print("Input:\n",X)
    print("Actual Output:\n",y)
    print("Predicted Output:\n",output)
    print("----- EPOCH",i+1,"Ends--------")

----- EPOCH 1 Starts--------
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.85885818]
 [0.85382751]
 [0.85803017]]
----- EPOCH 1 Ends--------
----- EPOCH 2 Starts--------
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.85904377]
 [0.85400775]
 [0.85821474]]
----- EPOCH 2 Ends--------
----- EPOCH 3 Starts--------
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.85922795]
 [0.85418663]
 [0.85839791]]
----- EPOCH 3 Ends--------
----- EPOCH 4 Starts--------
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.85941075]
 [0.85436418]
 [0.8585797 ]]
----- EPOCH 4 Ends--------
----- EPOCH 5 Starts--------