In [1]:
# Write a program to implement Support Vector Machine algorithm to classify the iris data set. Print 
# both correct and wrong predictions.

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [4]:
ir1=pd.read_csv('iris.csv')

In [5]:
ir1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
import category_encoders as ce

In [7]:
encoder=ce.OrdinalEncoder(cols=['Species'])
ir1=encoder.fit_transform(ir1)

In [8]:
ir1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        1
1   2            4.9           3.0            1.4           0.2        1
2   3            4.7           3.2            1.3           0.2        1
3   4            4.6           3.1            1.5           0.2        1
4   5            5.0           3.6            1.4           0.2        1

In [9]:
ir1.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
ir1_train,ir1_test=train_test_split(ir1,test_size=0.2,random_state=2)

In [11]:
ir1_train.reset_index(drop=True,inplace=True)
ir1_test.reset_index(drop=True,inplace=True)

In [12]:
x_train=ir1_train.drop(["Species"],1)
y_train=ir1_train["Species"]
x_test=ir1_test.drop(["Species"],1)
y_test=ir1_test["Species"]

In [13]:
from sklearn.svm import SVC # "Support vector classifier" 
classifier = SVC(kernel='linear', random_state=0) 
classifier.fit(x_train, y_train) 

SVC(kernel='linear', random_state=0)

In [14]:
y_pred= classifier.predict(x_test) 

In [15]:
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]


In [17]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8
           3       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy = accuracy_score(y_test, y_pred)*100
print('Accuracy of our model is ' + str(round(accuracy, 2)) + ' %.')

Accuracy of our model is 100.0 %.


In [20]:
print(" correct predicition",accuracy_score(y_test,y_pred))
print(" worng predicition",(1-accuracy_score(y_test,y_pred)))

 correct predicition 1.0
 worng predicition 0.0
